[WIP] Article about workflows
mozilla-services/servicedenuages.fr pull request #111
Opened 2016-11-14 15:06 UTC by leplatrem

2016-11-14 15:26 UTC, Natim requested changes

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +Par example, lorsque ces données étaient de simple fichiers JSON dans le dépôt Mercurial, leur
exemple

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +Par example, lorsque ces données étaient de simple fichiers JSON dans le dépôt Mercurial, leur
simples

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +modification passaient par le processus de revue de code classique et leur livraison
leurs modifications

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +Accélerer et fluidifier c'est super, mais il faut pas se louper!
se louper !

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +Accélerer et fluidifier c'est super, mais il faut pas se louper!
Plus généralement les espaces avant les !

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +par des contributeurs externes et validées par quelqu'un de confiance!
Plutôt que quelqu'un de confiance, par un QA je mettrais.

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +et la dernière est mise à jour si les changements sont approvés.
approuvées

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +qui va servir à demander la revue, approver ou rejetter les changements.
approuver

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +* Lorsqu'un changement a lieu sur les *records* de la *collection*, le status
statut

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +* ``user_id``: who?
qui ?

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +* ``date``: when?
Quand ?

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +* ``target``: what?
Quoi ?

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +d'expérimenter aussi le concept si l'on souhaite qu'il soit possible un jour
deux fois aussi

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +final ou configurer les clients pour pointer dessus.
ou tester dans un véritable client en faisant pointer la collection dessus.

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +Les workflows ont été implémentés en que fonctionnalité du `plugin de signatures <https://github.com/Kinto/kinto-signer/>`_,
En tant que fonctionnalités

2016-11-14 15:26 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +possible que nous en fassions un plugin à part entière à terme...
que nous en fassions un plugin spécifique dissocié de la signature.

2016-11-14 20:28 UTC, n1k0 approved these changes
Great post, a few nits

2016-11-14 20:28 UTC, n1k0 commented on content/2016.11.kinto-and-workflows.rst
> +* Lorsqu'un changement a lieu sur les *records* de la *collection*, le statut
Dans un article en français j'utiliserais le terme _enregistrements_ plutôt que _records_

2016-11-14 20:28 UTC, n1k0 commented on content/2016.11.kinto-and-workflows.rst
> +même que celle qui les approuve.
_soit la même_

2016-11-14 20:28 UTC, n1k0 commented on content/2016.11.kinto-and-workflows.rst
> +        data.forEach(r => console.log(`${r.user_id} ${r.action}d ${r.resource_name} ${r.target.id}`));
How about just

```js
console.log(r.user_id, r.action, r.resource_name, r.target.id)
```

2016-11-15 10:10 UTC, Natim commented on content/2016.11.kinto-and-workflows.rst
> +* ``user_id``: qui?
Il manque les espaces avant les ?

2016-11-15 10:17 UTC, merged