Prototyping an app with kinto
mozilla-services/servicedenuages.fr pull request #112
Opened 2016-12-15 17:11 UTC by magopian

2016-12-15 19:08 UTC, glasserc reviewed
I think this belongs more on http://www.kinto-storage.org/news.html than on this blog, but I think it's a decent enough idea for an article.

My biggest concern is that this app idea doesn't seem like a great fit for Kinto, which doesn't have any APIs to do aggregations, and even filtering is kind of dubious. So I'm not sure how you would test this idea or what results you might expect to discover as a result. Some remarks about that at the end would improve this.

2016-12-15 19:08 UTC, glasserc commented on content/2016.12.prototyping-an-app-with-kinto.md
> +Or, let's instead give it a try using the [kinto-admin].
I think there's something a bit rushed about these two paragraphs. How about inserting something like the following:

At the beginning of the first paragraph: `In order to build something like that, I'd normally have to ....`

At the beginning of the second paragraph: `But I'm not even sure it's a good idea! Maybe we can ...`

2016-12-15 19:08 UTC, glasserc commented on content/2016.12.prototyping-an-app-with-kinto.md
> +* a simple UI to create/read/update/delete entries (records)
I'm not sure what we need these things for. Some of these seem like requirements, i.e. user stories, and some like implementation details, i.e. needs of our desire to do this in Kinto. Maybe a better heading could clarify this.

2016-12-15 19:08 UTC, glasserc commented on content/2016.12.prototyping-an-app-with-kinto.md
> +Let's not submit this new collection just yet:
A colon at the end of this line seems a bit odd. Maybe an ellipsis would be better. Or maybe even better would be to explain why we are not submitting it yet.

2016-12-15 19:08 UTC, glasserc commented on content/2016.12.prototyping-an-app-with-kinto.md
> +As you can see while creating a collection, there's the possibility to add a JSON schema. This schema will be used to validate the data we'll submit, before it's stored in a record.
I don't like "there's the possibility" (sounds kind of French to me, maybe because "possibility" is being used as in "something is allowed" instead of "there is a statistical likelihood of this occuring"). How about "we have the option of adding"?

Also, maybe a comment about how this is used to automatically generate CRUD forms for our data? For this application, I think this is way more important than the fact that it validates.

2016-12-16 06:24 UTC, magopian commented
indeed, might be a good idea to move it to "the other website". I'm wondering what's the "rule" to decide which website should host which articles? Are we "deprecating" the "servicedesnuages" blog?

2016-12-16 08:34 UTC, magopian commented
Thanks for the review @glasserc, I believed I've addressed your comments. What do you think about the current form of the post?

When it looks good, i'll close this PR and re-open it on the [kinto-website](https://github.com/Kinto/kinto-website) repository.

2016-12-16 09:07 UTC, Natim commented
> indeed, might be a good idea to move it to "the other website". I'm wondering what's the "rule" to decide which website should host which articles? Are we "deprecating" the "servicedesnuages" blog?

No the rule is to blog here first and then cross blog on the kinto-storage blog if the article is related to kinto.

2016-12-16 10:57 UTC, Natim requested changes
Great article, few nits :)

2016-12-16 10:57 UTC, Natim commented on content/2016.12.prototyping-an-app-with-kinto.md
> +Let's sign in to the [admin] with the user/pass of our choice (the user will be "created" on the spot):
> the user will be "created" on the spot

It is not the truth, kinto doesn't handle any kind of user using the default basicauth backend.
If you talk about users people then want to change password for their user, while there is actually no user.

2016-12-16 10:57 UTC, Natim commented on content/2016.12.prototyping-an-app-with-kinto.md
> +Let's sign in to the [admin] with the user/pass of our choice (the user will be "created" on the spot):
Instead we could say, "this will link your data and permission to that session" or something like that.

2016-12-16 10:57 UTC, Natim commented on content/2016.12.prototyping-an-app-with-kinto.md
> +It'll also be used to automatically generate the CRUD forms for our data, straight into the admin.
`It will` more readable that `It'll`

2016-12-16 10:57 UTC, Natim commented on content/2016.12.prototyping-an-app-with-kinto.md
> +Note the `enum` attribute on the tag which will be rendered in the forms as a select, instead of a simple input text field.
For me tag means that you can select multiple one, in that case I would use category instead of tag.

2016-12-16 10:57 UTC, Natim commented on content/2016.12.prototyping-an-app-with-kinto.md
> +As you can see, without a single line of code and very small effort, we have a functional, albeit very basic, proof of concept!
Isn't JSON Schema a line of code? Should we tell them that they can use the Formbuilder to generate the proper JSON Schema?

2016-12-16 10:57 UTC, Natim commented on content/2016.12.prototyping-an-app-with-kinto.md
> +While this is a nice and easy way to have a proof of concept, the admin's role is not meant to fulfill all your needs. For example, kinto has no way to do aggregation, and filtering can't be done thr
tbh: Maybe that something we want to add to the admin, let's create issues there. And formulate that it is not possible yet, but we would be glad to have some help adding the feature.

2016-12-16 19:53 UTC, glasserc commented on content/2016.12.prototyping-an-app-with-kinto.md
> +Note the `enum` attribute on the tag which will be rendered in the forms as a select, instead of a simple input text field.
I'd also like `Note the enum attribute on the tag _field_` or `the category field` rather than on some specific record's tag.

2016-12-16 19:53 UTC, glasserc commented on content/2016.12.prototyping-an-app-with-kinto.md
> +It'll also be used to automatically generate the CRUD forms for our data, straight into the admin.
`It'll` is more casual if a tiny bit nonstandard. We use `we'll` in the line just above; would you also change this?

To be honest I don't like either "it will" or "it'll" here, maybe because there are too many possible targets for the reference. The easiest solution is to just put `The schema will`.

2016-12-16 19:53 UTC, glasserc commented on content/2016.12.prototyping-an-app-with-kinto.md
> +The `ui:order` will be used to display the fields in the order we want (json objects attributes aren't ordered), and we also specify that we'd like a `textarea` for the comment field, instead of a si
`JSON` should be capitalized.

2016-12-19 10:51 UTC, magopian commented on content/2016.12.prototyping-an-app-with-kinto.md
> +As you can see, without a single line of code and very small effort, we have a functional, albeit very basic, proof of concept!
Good idea, i'll add a link. However, I don't see a way to download the UI schema, only the schema itself? Also, no way to make a field be a number.

2016-12-19 11:00 UTC, magopian commented on content/2016.12.prototyping-an-app-with-kinto.md
> +While this is a nice and easy way to have a proof of concept, the admin's role is not meant to fulfill all your needs. For example, kinto has no way to do aggregation, and filtering can't be done thr
https://github.com/Kinto/kinto/issues/989

2016-12-19 11:04 UTC, magopian commented
@glasserc @Natim i believe I addressed your comments (but the change from `tag` to `category`: it would need new screenshots, and E_TOO_LAZY)

2016-12-19 11:15 UTC, leplatrem commented on content/2016.12.prototyping-an-app-with-kinto.md
> +While this is a nice and easy way to have a proof of concept, the admin's role is not meant to fulfill all your needs. For example, Kinto has no way to do aggregation (yet, but there's an open issue
Do we have a use-case for those aggregation features? Can't we avoid mentioning those missing features in an introductory article, especially if they were never requested before?

2016-12-19 11:17 UTC, Natim commented on content/2016.12.prototyping-an-app-with-kinto.md
> +While this is a nice and easy way to have a proof of concept, the admin's role is not meant to fulfill all your needs. For example, Kinto has no way to do aggregation (yet, but there's an open issue
Why do you think we need aggregation in the admin? Isn't filtering enough for an admin?

2016-12-19 11:24 UTC, magopian commented on content/2016.12.prototyping-an-app-with-kinto.md
> +While this is a nice and easy way to have a proof of concept, the admin's role is not meant to fulfill all your needs. For example, Kinto has no way to do aggregation (yet, but there's an open issue
@natim I'm talking about the aggregation at kinto's level, not in the admin. Regarding filtering in the admin, there's already an [open issue](https://github.com/Kinto/kinto-admin/issues/7)

@leplatrem you're right, I'll reword it

2016-12-19 11:28 UTC, Natim commented
> E_TOO_LAZY

It worth it because your article will be there for years to come and it will only take your 10 minutes to refresh the screenshots :)

2016-12-19 12:22 UTC, magopian commented
![ok](http://www.memes.at/faces/okay.gif)

2016-12-19 13:30 UTC, merged